/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene.gltf
Author: nenkea (https://sketchfab.com/nenkea)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-future-building-2-simple-dome-d885fdb25ed846779fc711917fbeeed2
Title: Sci- Fi / Future Building 2: Simple Dome
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={1.91}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Main} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Poles} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Light} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Ring} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Light_Mirror} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
