/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene.gltf
Author: Aysa (https://sketchfab.com/Aysa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vending-machine-c1fe68faefd94a8fa9cafcfeb4737e51
Title: Vending machine
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.ContrastpolySurface1_Contrastm_vendingmachine_glass_0.geometry} material={materials.Contrastm_vendingmachine_glass} position={[-18.7, 0, 0.93]} />
        <mesh geometry={nodes.polySurface1_Contrastm_vendingmachine_glass_0.geometry} material={materials.Contrastm_vendingmachine_glass} position={[-150.46, 0, 0.93]} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_can_aluminium_1_0.geometry} material={materials.Contrastm_vendingmachine_can_aluminium_1} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_aluminium_2_0.geometry} material={materials.Contrastm_vendingmachine_aluminium_2} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_can_aluminium_6_0.geometry} material={materials.Contrastm_vendingmachine_can_aluminium_6} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_bottle_plastic_2_0.geometry} material={materials.Contrastm_vendingmachine_bottle_plastic_2} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_polyethylene_4_0.geometry} material={materials.Contrastm_vendingmachine_polyethylene_4} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_bottle_cola_0.geometry} material={materials.Contrastm_vendingmachine_bottle_cola} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_bottle_plastic1_0.geometry} material={materials.Contrastm_vendingmachine_bottle_plastic1} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_can_aluminium_7_0.geometry} material={materials.Contrastm_vendingmachine_can_aluminium_7} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_polyethylene_3_0.geometry} material={materials.Contrastm_vendingmachine_polyethylene_3} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_metal_1_0.geometry} material={materials.Contrastm_vendingmachine_metal_1} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_m_vendingmachine_metal_4_0.geometry} material={materials.Contrastm_m_vendingmachine_metal_4} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_metal_2_0.geometry} material={materials.Contrastm_vendingmachine_metal_2} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_metal_3_0.geometry} material={materials.Contrastm_vendingmachine_metal_3} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastlambert2_0.geometry} material={materials.Contrastlambert2} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_screen_0.geometry} material={materials.Contrastm_vendingmachine_screen} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_plastic_1_0.geometry} material={materials.Contrastm_vendingmachine_plastic_1} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_plastic_2_0.geometry} material={materials.Contrastm_vendingmachine_plastic_2} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_light_0.geometry} material={materials.Contrastm_vendingmachine_light} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_paper_3_0.geometry} material={materials.Contrastm_vendingmachine_paper_3} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_m_vendingmachine_paper_1_0.geometry} material={materials.Contrastm_m_vendingmachine_paper_1} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_paper_2_0.geometry} material={materials.Contrastm_vendingmachine_paper_2} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_polyethylene_1_0.geometry} material={materials.Contrastm_vendingmachine_polyethylene_1} />
        <mesh geometry={nodes.ContrastambientLight1_Contrastm_vendingmachine_polyethylene_2_0.geometry} material={materials.Contrastm_vendingmachine_polyethylene_2} />
        <group position={[109.35, 0, 0]}>
          <mesh geometry={nodes.polySurface38_m_vendingmachine_can_aluminium_1_0.geometry} material={materials.m_vendingmachine_can_aluminium_1} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_aluminium_2_0.geometry} material={materials.m_vendingmachine_aluminium_2} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_bottle_plastic1_0.geometry} material={materials.m_vendingmachine_bottle_plastic1} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_bottle_cola_0.geometry} material={materials.m_vendingmachine_bottle_cola} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_bottle_plastic_2_0.geometry} material={materials.m_vendingmachine_bottle_plastic_2} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_can_aluminium_7_0.geometry} material={materials.m_vendingmachine_can_aluminium_7} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_can_aluminium_6_0.geometry} material={materials.m_vendingmachine_can_aluminium_6} />
          <mesh geometry={nodes.polySurface38_lambert2_0.geometry} material={materials.lambert2} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_metal_3_0.geometry} material={materials.m_vendingmachine_metal_3} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_screen_0.geometry} material={materials.m_vendingmachine_screen} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_metal_2_0.geometry} material={materials.m_vendingmachine_metal_2} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_paper_2_0.geometry} material={materials.m_vendingmachine_paper_2} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_polyethylene_1_0.geometry} material={materials.m_vendingmachine_polyethylene_1} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_polyethylene_2_0.geometry} material={materials.m_vendingmachine_polyethylene_2} />
          <mesh geometry={nodes.polySurface38_m_m_vendingmachine_metal_4_0.geometry} material={materials.m_m_vendingmachine_metal_4} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_plastic_1_0.geometry} material={materials.m_vendingmachine_plastic_1} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_metal_1_0.geometry} material={materials.m_vendingmachine_metal_1} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_plastic_2_0.geometry} material={materials.m_vendingmachine_plastic_2} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_light_0.geometry} material={materials.m_vendingmachine_light} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_paper_3_0.geometry} material={materials.m_vendingmachine_paper_3} />
          <mesh geometry={nodes.polySurface38_m_m_vendingmachine_paper_1_0.geometry} material={materials.m_m_vendingmachine_paper_1} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_glass_0.geometry} material={materials.m_vendingmachine_glass} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_polyethylene_3_0.geometry} material={materials.m_vendingmachine_polyethylene_3} />
          <mesh geometry={nodes.polySurface38_m_vendingmachine_polyethylene_4_0.geometry} material={materials.m_vendingmachine_polyethylene_4} />
        </group>
        <group position={[-19.13, 0, 0]}>
          <mesh geometry={nodes.polySurface394_m_vendingmachine_bottle_plastic_3_0.geometry} material={materials.m_vendingmachine_bottle_plastic_3} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_bottle_plastic2_0.geometry} material={materials.m_vendingmachine_bottle_plastic2} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_bottle_cola1_0.geometry} material={materials.m_vendingmachine_bottle_cola1} />
          <mesh geometry={nodes.polySurface394_m_m_vendingmachine_metal_5_0.geometry} material={materials.m_m_vendingmachine_metal_5} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_metal_4_0.geometry} material={materials.m_vendingmachine_metal_4} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_plastic_3_0.geometry} material={materials.m_vendingmachine_plastic_3} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_metal_5_0.geometry} material={materials.m_vendingmachine_metal_5} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_light1_0.geometry} material={materials.m_vendingmachine_light1} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_screen1_0.geometry} material={materials.m_vendingmachine_screen1} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_paper_4_0.geometry} material={materials.m_vendingmachine_paper_4} />
          <mesh geometry={nodes.polySurface394_lambert3_0.geometry} material={materials.lambert3} />
          <mesh geometry={nodes.polySurface394_m_m_vendingmachine_paper_2_0.geometry} material={materials.m_m_vendingmachine_paper_2} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_plastic_4_0.geometry} material={materials.m_vendingmachine_plastic_4} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_can_aluminium_8_0.geometry} material={materials.m_vendingmachine_can_aluminium_8} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_can_aluminium_9_0.geometry} material={materials.m_vendingmachine_can_aluminium_9} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_metal_6_0.geometry} material={materials.m_vendingmachine_metal_6} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_polyethylene_5_0.geometry} material={materials.m_vendingmachine_polyethylene_5} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_polyethylene_6_0.geometry} material={materials.m_vendingmachine_polyethylene_6} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_paper_5_0.geometry} material={materials.m_vendingmachine_paper_5} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_aluminium_3_0.geometry} material={materials.m_vendingmachine_aluminium_3} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_can_aluminium_10_0.geometry} material={materials.m_vendingmachine_can_aluminium_10} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_polyethylene_7_0.geometry} material={materials.m_vendingmachine_polyethylene_7} />
          <mesh geometry={nodes.polySurface394_m_vendingmachine_polyethylene_8_0.geometry} material={materials.m_vendingmachine_polyethylene_8} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
