/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene.gltf
Author: Tiko (https://sketchfab.com/tikoavp)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fashion-figure-base-644b113218b94c94b5f07be0b6f455a3
Title: Fashion Figure Base
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useBox, useSphere } from '@react-three/cannon';

export function ModelTest(props) {
  const { nodes, materials } = useGLTF('/models/human/scene.gltf');
  // const [ref, api] = useSphere(() => ({ mass: 1, ...props }));
  const [ref, api] = useBox(() => ({ mass: 1, ...props }));

  return (
    <mesh ref={ref}>
      <group dispose={null}>
        <group scale={0.0001}>
          <mesh
            geometry={nodes.Shoe001_Material001_0.geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.Body002_Material001_0.geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.Arm001_Material001_0.geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.Torus005_Material001_0.geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.Retopo_Mesh007_Material001_0.geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.Sphere001_Material001_0.geometry}
            material={materials['Material.001']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </mesh>
  );
}

useGLTF.preload('/models/human/scene.gltf');
