/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene.gltf
Author: Unity Fan youtube channel (https://sketchfab.com/unityfan777)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-city-public-domain-cc0-b353532235bb4c45afeac578187c9be1
Title: Sci-Fi City - public domain (CC0)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-3108.81, -320.71, 900.13]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100}>
          <mesh geometry={nodes.building001_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building001_metal1_0.geometry} material={materials.metal1} />
          <mesh geometry={nodes.building001_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building001_windows_lit1_0.geometry} material={materials.windows_lit1} />
        </group>
        <group position={[-3715.43, 1213.89, -400.52]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.building002_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building002_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building002_metal3_0.geometry} material={materials.metal3} />
          <mesh geometry={nodes.building002_windows_lit1_0.geometry} material={materials.windows_lit1} />
        </group>
        <group position={[-4381.12, 0, 332.05]} rotation={[-Math.PI / 2, 0, -Math.PI / 4]} scale={100}>
          <mesh geometry={nodes.building006_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building006_windows_lit1_0.geometry} material={materials.windows_lit1} />
          <mesh geometry={nodes.building006_metal3_0.geometry} material={materials.metal3} />
          <mesh geometry={nodes.building006_windows_unlit_0.geometry} material={materials.windows_unlit} />
        </group>
        <group position={[-3182.85, -219.08, -702.42]} rotation={[-Math.PI / 2, 0, 2.36]} scale={100}>
          <mesh geometry={nodes.building007_metal1_0.geometry} material={materials.metal1} />
          <mesh geometry={nodes.building007_windows_lit1_0.geometry} material={materials.windows_lit1} />
          <mesh geometry={nodes.building007_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building007_windows_unlit_0.geometry} material={materials.windows_unlit} />
        </group>
        <group position={[-4810.39, 0, -711.62]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.building011_windows_lit1_0.geometry} material={materials.windows_lit1} />
          <mesh geometry={nodes.building011_metal3_0.geometry} material={materials.metal3} />
          <mesh geometry={nodes.building011_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building011_windows_unlit_0.geometry} material={materials.windows_unlit} />
        </group>
        <group position={[-4808.64, 873.32, -714.75]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100}>
          <mesh geometry={nodes.building012_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building012_metal3_0.geometry} material={materials.metal3} />
          <mesh geometry={nodes.building012_windows_lit1_0.geometry} material={materials.windows_lit1} />
        </group>
        <group position={[-3929.75, 0, 208.34]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100}>
          <mesh geometry={nodes.building013_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building013_metal4_0.geometry} material={materials.metal4} />
          <mesh geometry={nodes.building013_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building013_windows_lit1_0.geometry} material={materials.windows_lit1} />
        </group>
        <group position={[-6234.88, 0, -406.88]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100}>
          <mesh geometry={nodes.building015_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building015_metal3_0.geometry} material={materials.metal3} />
          <mesh geometry={nodes.building015_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building015_windows_lit1_0.geometry} material={materials.windows_lit1} />
        </group>
        <group position={[-4847.38, 0, 651.73]} rotation={[-Math.PI / 2, 0, -Math.PI / 4]} scale={100}>
          <mesh geometry={nodes.building017_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building017_metal3_0.geometry} material={materials.metal3} />
          <mesh geometry={nodes.building017_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building017_windows_lit4_0.geometry} material={materials.windows_lit4} />
        </group>
        <group position={[-3726.32, -163.5, -1322.19]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.building018_windows_lit1_0.geometry} material={materials.windows_lit1} />
          <mesh geometry={nodes.building018_metal1_0.geometry} material={materials.metal1} />
          <mesh geometry={nodes.building018_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building018_windows_unlit_0.geometry} material={materials.windows_unlit} />
        </group>
        <group position={[-4426.68, 0, -363.68]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.building019_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building019_windows_lit1_0.geometry} material={materials.windows_lit1} />
          <mesh geometry={nodes.building019_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building019_metal3_0.geometry} material={materials.metal3} />
        </group>
        <group position={[-3718.55, 0, -402.27]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.building020_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building020_windows_lit1_0.geometry} material={materials.windows_lit1} />
          <mesh geometry={nodes.building020_metal3_0.geometry} material={materials.metal3} />
          <mesh geometry={nodes.building020_dark_0.geometry} material={materials.dark} />
        </group>
        <group position={[-3600, 0, 400]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.building021_metal3_0.geometry} material={materials.metal3} />
          <mesh geometry={nodes.building021_windows_lit4_0.geometry} material={materials.windows_lit4} />
          <mesh geometry={nodes.building021_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building021_windows_unlit_0.geometry} material={materials.windows_unlit} />
        </group>
        <group position={[-4362.34, 0, 823.61]} rotation={[-Math.PI / 2, 0, Math.PI / 4]} scale={100}>
          <mesh geometry={nodes.building022_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building022_metal1_0.geometry} material={materials.metal1} />
          <mesh geometry={nodes.building022_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building022_windows_lit2_0.geometry} material={materials.windows_lit2} />
        </group>
        <group position={[-5591.39, 0, -377.01]} rotation={[-Math.PI / 2, 0, Math.PI / 4]} scale={100}>
          <mesh geometry={nodes.building023_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building023_metal1_0.geometry} material={materials.metal1} />
          <mesh geometry={nodes.building023_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building023_windows_lit1_0.geometry} material={materials.windows_lit1} />
        </group>
        <group position={[-3898.3, 0, 885.19]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.building025_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building025_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building025_metal4_0.geometry} material={materials.metal4} />
          <mesh geometry={nodes.building025_windows_lit1_0.geometry} material={materials.windows_lit1} />
        </group>
        <group position={[-4380.15, 1213.89, 335.49]} rotation={[-Math.PI / 2, 0, Math.PI / 4]} scale={100}>
          <mesh geometry={nodes.building026_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building026_windows_lit1_0.geometry} material={materials.windows_lit1} />
          <mesh geometry={nodes.building026_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building026_metal3_0.geometry} material={materials.metal3} />
        </group>
        <group position={[-5173.8, 0, -975.73]} rotation={[-Math.PI / 2, 0, Math.PI / 4]} scale={100}>
          <mesh geometry={nodes.building027_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building027_metal3_0.geometry} material={materials.metal3} />
          <mesh geometry={nodes.building027_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building027_windows_lit1_0.geometry} material={materials.windows_lit1} />
        </group>
        <group position={[-5370.52, 0, 965.7]} rotation={[-Math.PI / 2, 0, 2.36]} scale={100}>
          <mesh geometry={nodes.building028_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building028_metal1_0.geometry} material={materials.metal1} />
          <mesh geometry={nodes.building028_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building028_windows_lit2_0.geometry} material={materials.windows_lit2} />
        </group>
        <group position={[-4726.56, 0, -19.91]} rotation={[-Math.PI / 2, 0, 2.36]} scale={100}>
          <mesh geometry={nodes.building029_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building029_metal1_0.geometry} material={materials.metal1} />
          <mesh geometry={nodes.building029_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building029_windows_lit1_0.geometry} material={materials.windows_lit1} />
        </group>
        <group position={[-2918.43, -115.59, 123.51]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.building030_metal1_0.geometry} material={materials.metal1} />
          <mesh geometry={nodes.building030_windows_lit2_0.geometry} material={materials.windows_lit2} />
          <mesh geometry={nodes.building030_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building030_windows_unlit_0.geometry} material={materials.windows_unlit} />
        </group>
        <group position={[-3335.89, 0, -27.66]} rotation={[-Math.PI / 2, 0, Math.PI / 4]} scale={100}>
          <mesh geometry={nodes.building031_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building031_windows_lit1_0.geometry} material={materials.windows_lit1} />
          <mesh geometry={nodes.building031_metal4_0.geometry} material={materials.metal4} />
          <mesh geometry={nodes.building031_dark_0.geometry} material={materials.dark} />
        </group>
        <group position={[-3541.28, 0, 1328.39]} rotation={[-Math.PI / 2, 0, Math.PI / 4]} scale={100}>
          <mesh geometry={nodes.building032_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building032_windows_lit4_0.geometry} material={materials.windows_lit4} />
          <mesh geometry={nodes.building032_metal3_0.geometry} material={materials.metal3} />
          <mesh geometry={nodes.building032_dark_0.geometry} material={materials.dark} />
        </group>
        <group position={[-4364.36, 0, 1696.57]} rotation={[-Math.PI / 2, 0, -2.36]} scale={100}>
          <mesh geometry={nodes.building033_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building033_windows_lit1_0.geometry} material={materials.windows_lit1} />
          <mesh geometry={nodes.building033_metal1_0.geometry} material={materials.metal1} />
          <mesh geometry={nodes.building033_dark_0.geometry} material={materials.dark} />
        </group>
        <group position={[-4226.45, 0, -830.17]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.building034_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building034_windows_lit4_0.geometry} material={materials.windows_lit4} />
          <mesh geometry={nodes.building034_metal3_0.geometry} material={materials.metal3} />
          <mesh geometry={nodes.building034_dark_0.geometry} material={materials.dark} />
        </group>
        <group position={[-4626.45, 0, -1247.87]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100}>
          <mesh geometry={nodes.building009_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building009_windows_lit2_0.geometry} material={materials.windows_lit2} />
          <mesh geometry={nodes.building009_metal1_0.geometry} material={materials.metal1} />
          <mesh geometry={nodes.building009_dark_0.geometry} material={materials.dark} />
        </group>
        <group position={[-5089.05, 0, -339.43]} rotation={[-Math.PI / 2, 0, Math.PI / 4]} scale={100}>
          <mesh geometry={nodes.building014_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building014_windows_lit1_0.geometry} material={materials.windows_lit1} />
          <mesh geometry={nodes.building014_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building014_metal3_0.geometry} material={materials.metal3} />
        </group>
        <group position={[-5170.35, 1213.89, -976.71]} rotation={[-Math.PI / 2, 0, 2.36]} scale={100}>
          <mesh geometry={nodes.building024_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building024_windows_lit1_0.geometry} material={materials.windows_lit1} />
          <mesh geometry={nodes.building024_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building024_metal3_0.geometry} material={materials.metal3} />
        </group>
        <group position={[-4944.06, 0, 1702.11]} rotation={[-Math.PI / 2, 0, -Math.PI / 4]} scale={100}>
          <mesh geometry={nodes.building035_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building035_windows_lit1_0.geometry} material={materials.windows_lit1} />
          <mesh geometry={nodes.building035_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building035_metal3_0.geometry} material={materials.metal3} />
        </group>
        <group position={[-5250.52, 0, 1380.3]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.building008_metal4_0.geometry} material={materials.metal4} />
          <mesh geometry={nodes.building008_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building008_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.building008_windows_lit1_0.geometry} material={materials.windows_lit1} />
        </group>
        <group position={[-4800.32, 0, 1158.69]} rotation={[-Math.PI / 2, 0, 2.36]} scale={100}>
          <mesh geometry={nodes.building_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building_windows_lit1_0.geometry} material={materials.windows_lit1} />
          <mesh geometry={nodes.building_metal3_0.geometry} material={materials.metal3} />
          <mesh geometry={nodes.building_dark_0.geometry} material={materials.dark} />
        </group>
        <group position={[-5355.27, 0, 306.23]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.building004_windows_unlit_0.geometry} material={materials.windows_unlit} />
          <mesh geometry={nodes.building004_windows_lit1_0.geometry} material={materials.windows_lit1} />
          <mesh geometry={nodes.building004_metal1_0.geometry} material={materials.metal1} />
          <mesh geometry={nodes.building004_dark_0.geometry} material={materials.dark} />
        </group>
        <mesh geometry={nodes.cloud012_cloud_0.geometry} material={materials.cloud} position={[-2524.31, -314.28, 2326.37]} rotation={[0, Math.PI / 2, 0]} scale={1061.91} />
        <mesh geometry={nodes.cloud019_cloud_0.geometry} material={materials.cloud} position={[-3350.56, -137.69, -1245.08]} rotation={[0, Math.PI / 2, 0]} scale={1198.49} />
        <mesh geometry={nodes.cloud010_cloud_0.geometry} material={materials.cloud} position={[-2712.91, -137.69, -1245.08]} rotation={[0, Math.PI / 2, 0]} scale={828.87} />
        <mesh geometry={nodes.cloud011_cloud_0.geometry} material={materials.cloud} position={[-2504.04, -137.69, 1231.47]} rotation={[0, Math.PI / 2, 0]} scale={828.87} />
        <mesh geometry={nodes.cloud013_cloud_0.geometry} material={materials.cloud} position={[-2578.68, -68.92, 352.14]} rotation={[0, Math.PI / 2, 0]} scale={584.98} />
        <mesh geometry={nodes.cloud014_cloud_0.geometry} material={materials.cloud} position={[-5763.72, -137.69, -1245.08]} rotation={[0, Math.PI / 2, 0]} scale={2332.6} />
        <mesh geometry={nodes.cloud_cloud_0.geometry} material={materials.cloud} position={[-2581.86, -137.69, -840.42]} rotation={[0, Math.PI / 2, 0]} scale={463.25} />
        <mesh geometry={nodes.cloud001_cloud_0.geometry} material={materials.cloud} position={[-2691.82, -137.69, 0]} rotation={[0, Math.PI / 2, 0]} scale={828.87} />
        <mesh geometry={nodes.cloud003_cloud_0.geometry} material={materials.cloud} position={[-3001.98, -137.69, -950.08]} rotation={[0, Math.PI / 2, 0]} scale={828.87} />
        <mesh geometry={nodes.cloud004_cloud_0.geometry} material={materials.cloud} position={[-3001.98, -137.69, 972.92]} rotation={[0, Math.PI / 2, 0]} scale={828.87} />
        <mesh geometry={nodes.cloud006_cloud_0.geometry} material={materials.cloud} position={[-3753.91, -141.37, 1921.21]} rotation={[0, Math.PI / 2, 0]} scale={914.39} />
        <mesh geometry={nodes.cloud005_cloud_0.geometry} material={materials.cloud} position={[-3999.33, -16.45, 1990.46]} rotation={[0, Math.PI / 2, 0]} scale={1086.21} />
        <mesh geometry={nodes.cloud023_cloud_0.geometry} material={materials.cloud} position={[-7213.56, -137.69, 2045.36]} rotation={[0, Math.PI / 2, 0]} scale={2332.6} />
        <mesh geometry={nodes.cloud024_cloud_0.geometry} material={materials.cloud} position={[-6715.07, -137.69, 2045.36]} rotation={[0, Math.PI / 2, 0]} scale={828.87} />
        <mesh geometry={nodes.cloud025_cloud_0.geometry} material={materials.cloud} position={[-6318.83, -137.69, 2126.94]} rotation={[0, Math.PI / 2, 0]} scale={978.18} />
        <mesh geometry={nodes.cloud029_cloud_0.geometry} material={materials.cloud} position={[-6548.14, -137.69, 285.7]} rotation={[0, Math.PI / 2, 0]} scale={1473.89} />
        <mesh geometry={nodes.cloud009_cloud_0.geometry} material={materials.cloud} position={[-4791.62, 299.21, 1921.21]} rotation={[0, Math.PI / 2, 0]} scale={914.39} />
        <mesh geometry={nodes.cloud026_cloud_0.geometry} material={materials.cloud} position={[-5156.57, -137.69, 2143.77]} rotation={[0, Math.PI / 2, 0]} scale={781.49} />
        <mesh geometry={nodes.cloud027_cloud_0.geometry} material={materials.cloud} position={[-5698.33, -137.69, 1324.35]} rotation={[0, Math.PI / 2, 0]} scale={978.18} />
        <mesh geometry={nodes.cloud008_cloud_0.geometry} material={materials.cloud} position={[-4840.65, -137.69, 972.92]} rotation={[0, Math.PI / 2, 0]} scale={828.87} />
        <mesh geometry={nodes.cloud016_cloud_0.geometry} material={materials.cloud} position={[-3626.35, -137.69, 1231.47]} rotation={[0, Math.PI / 2, 0]} scale={828.87} />
        <mesh geometry={nodes.cloud028_cloud_0.geometry} material={materials.cloud} position={[-6177.19, -137.69, 582.45]} rotation={[0, Math.PI / 2, 0]} scale={978.18} />
        <mesh geometry={nodes.cloud002_cloud_0.geometry} material={materials.cloud} position={[-4080.12, 308.69, -368.27]} rotation={[0, Math.PI / 2, 0]} scale={1452.85} />
        <mesh geometry={nodes.cloud017_cloud_0.geometry} material={materials.cloud} position={[-3454.96, -49.38, 162.07]} rotation={[0, Math.PI / 2, 0]} scale={1061.91} />
        <mesh geometry={nodes.cloud021_cloud_0.geometry} material={materials.cloud} position={[-6103.22, -137.69, -1163.5]} rotation={[0, Math.PI / 2, 0]} scale={978.18} />
        <mesh geometry={nodes.cloud007_cloud_0.geometry} material={materials.cloud} position={[-4530.49, -137.69, 0]} rotation={[0, Math.PI / 2, 0]} scale={828.87} />
        <mesh geometry={nodes.cloud015_cloud_0.geometry} material={materials.cloud} position={[-3814.12, -137.69, -1245.08]} rotation={[0, Math.PI / 2, 0]} scale={828.87} />
        <mesh geometry={nodes.cloud018_cloud_0.geometry} material={materials.cloud} position={[-3700.99, -432.64, 352.14]} rotation={[0, Math.PI / 2, 0]} scale={584.98} />
        <mesh geometry={nodes.cloud020_cloud_0.geometry} material={materials.cloud} position={[-6499.47, -137.69, -1245.08]} rotation={[0, Math.PI / 2, 0]} scale={828.87} />
        <mesh geometry={nodes.cloud022_cloud_0.geometry} material={materials.cloud} position={[-5217.48, -137.69, -1956]} rotation={[0, Math.PI / 2, 0]} scale={781.49} />
        <mesh geometry={nodes.stars001_stars_0.geometry} material={materials.stars} position={[-4776.12, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={124.93} />
        <mesh geometry={nodes.stars_stars_0.geometry} material={materials.stars} position={[-4776.12, 1568.64, 0]} rotation={[-1.7, 0.12, 0.46]} scale={130.89} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
