/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene.gltf
Author: 打螺丝 (https://sketchfab.com/youoyouyou)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-corridor-fa603622f0574fa584a5289dc506b3bd
Title: Sci-fi Corridor
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[241.65, 180.2, 2492.85]} scale={[958.52, 958.52, 3.5]}>
          <mesh geometry={nodes.pCube74_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.pCube74_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group position={[-67.32, -28.36, -637.5]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-70.65, -28.36, -637.5]} scale={100}>
          <mesh geometry={nodes.polySurface142_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface142_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-70.65, -28.36, -636.4]} scale={100}>
          <mesh geometry={nodes.polySurface144_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface144_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group position={[-70.65, -28.36, -283.1]} scale={100}>
          <mesh geometry={nodes.polySurface170_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface170_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.polySurface187_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface187_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.polySurface197_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface197_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group position={[-70.65, -28.36, -283.81]} scale={100}>
          <mesh geometry={nodes.polySurface142001_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface142001_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[182.17, -28.36, -637.5]} scale={100}>
          <mesh geometry={nodes.polySurface142002_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface142002_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[182.17, -28.36, -283.81]} scale={100}>
          <mesh geometry={nodes.polySurface142003_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface142003_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-67.32, -28.36, -453.29]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141001_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141001_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-67.32, -28.36, -269.07]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141002_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141002_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-27.06, 605.53, 249.14]} rotation={[Math.PI, 0, -Math.PI]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141003_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141003_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[522.28, -28.36, -637.5]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141004_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141004_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[522.28, -28.36, -453.29]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141005_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141005_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[522.28, -28.36, -269.07]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141006_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141006_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[562.53, 605.53, 249.14]} rotation={[Math.PI, 0, -Math.PI]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141007_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141007_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-67.32, -28.36, 79.91]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141008_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141008_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-70.65, -28.36, 79.91]} scale={100}>
          <mesh geometry={nodes.polySurface142004_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface142004_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-70.65, -28.36, 81.01]} scale={100}>
          <mesh geometry={nodes.polySurface144001_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface144001_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group position={[-70.65, -28.36, 434.31]} scale={100}>
          <mesh geometry={nodes.polySurface170001_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface170001_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.polySurface187001_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface187001_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.polySurface197001_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface197001_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group position={[-70.65, -28.36, 433.6]} scale={100}>
          <mesh geometry={nodes.polySurface142005_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface142005_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[182.17, -28.36, 79.91]} scale={100}>
          <mesh geometry={nodes.polySurface142006_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface142006_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[182.17, -28.36, 433.6]} scale={100}>
          <mesh geometry={nodes.polySurface142007_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface142007_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-67.32, -28.36, 264.13]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141009_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141009_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-67.32, -28.36, 448.35]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141010_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141010_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-27.06, 605.53, 966.56]} rotation={[Math.PI, 0, -Math.PI]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141011_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141011_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[522.28, -28.36, 79.91]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141012_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141012_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[522.28, -28.36, 264.13]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141013_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141013_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[522.28, -28.36, 448.35]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141014_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141014_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[562.53, 605.53, 966.56]} rotation={[Math.PI, 0, -Math.PI]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141015_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141015_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-67.32, -28.36, 797.32]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141016_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141016_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-70.65, -28.36, 797.32]} scale={100}>
          <mesh geometry={nodes.polySurface142008_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface142008_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-70.65, -28.36, 798.43]} scale={100}>
          <mesh geometry={nodes.polySurface144002_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface144002_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group position={[-70.65, -28.36, 1151.73]} scale={100}>
          <mesh geometry={nodes.polySurface170002_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface170002_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.polySurface187002_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface187002_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.polySurface197002_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface197002_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group position={[-70.65, -28.36, 1151.02]} scale={100}>
          <mesh geometry={nodes.polySurface142009_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface142009_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[182.17, -28.36, 797.32]} scale={100}>
          <mesh geometry={nodes.polySurface142010_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface142010_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[182.17, -28.36, 1151.02]} scale={100}>
          <mesh geometry={nodes.polySurface142011_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface142011_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-67.32, -28.36, 981.54]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141017_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141017_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-67.32, -28.36, 1165.76]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141018_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141018_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-27.06, 605.53, 1683.97]} rotation={[Math.PI, 0, -Math.PI]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141019_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141019_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[522.28, -28.36, 797.32]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141020_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141020_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[522.28, -28.36, 981.54]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141021_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141021_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[522.28, -28.36, 1165.76]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141022_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141022_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[562.53, 605.53, 1683.97]} rotation={[Math.PI, 0, -Math.PI]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141023_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141023_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-67.32, -28.36, 1514.74]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141024_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141024_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-70.65, -28.36, 1514.74]} scale={100}>
          <mesh geometry={nodes.polySurface142012_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface142012_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-70.65, -28.36, 1515.84]} scale={100}>
          <mesh geometry={nodes.polySurface144003_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface144003_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group position={[-70.65, -28.36, 1869.14]} scale={100}>
          <mesh geometry={nodes.polySurface170003_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface170003_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.polySurface187003_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface187003_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.polySurface197003_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface197003_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group position={[-70.65, -28.36, 1868.43]} scale={100}>
          <mesh geometry={nodes.polySurface142013_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface142013_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[182.17, -28.36, 1514.74]} scale={100}>
          <mesh geometry={nodes.polySurface142014_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface142014_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[182.17, -28.36, 1868.43]} scale={100}>
          <mesh geometry={nodes.polySurface142015_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface142015_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-67.32, -28.36, 1698.95]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141025_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141025_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-67.32, -28.36, 1883.17]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141026_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141026_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[-27.06, 605.53, 2401.39]} rotation={[Math.PI, 0, -Math.PI]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141027_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141027_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[522.28, -28.36, 1514.74]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141028_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141028_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[522.28, -28.36, 1698.95]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141029_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141029_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[522.28, -28.36, 1883.17]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141030_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141030_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <group position={[562.53, 605.53, 2401.39]} rotation={[Math.PI, 0, -Math.PI]} scale={[96.81, 100, 100]}>
          <mesh geometry={nodes.polySurface141031_matt2002_0.geometry} material={materials['matt2.002']} />
          <mesh geometry={nodes.polySurface141031_matt2003_0.geometry} material={materials['matt2.003']} />
        </group>
        <mesh geometry={nodes.polySurface143_matt2002_0.geometry} material={materials['matt2.002']} position={[268.96, 623.77, -13.88]} scale={[65.09, 65.09, 99.49]} />
        <mesh geometry={nodes.polySurface145_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, -635.59]} scale={[100, 100, 95.67]} />
        <mesh geometry={nodes.polySurface146_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, -637.5]} scale={100} />
        <mesh geometry={nodes.polySurface147_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, -641.8]} scale={[100, 100, 96.7]} />
        <mesh geometry={nodes.polySurface165_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, -278.08]} scale={[100, 100, 95.67]} />
        <mesh geometry={nodes.polySurface166_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, -282.99]} scale={[100, 100, 96.7]} />
        <mesh geometry={nodes.polySurface175_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, 84.18]} scale={100} />
        <mesh geometry={nodes.polySurface179_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, -278.08]} scale={[-100, 100, 95.67]} />
        <mesh geometry={nodes.polySurface184_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, -282.99]} scale={[-100, 100, 96.7]} />
        <mesh geometry={nodes.polySurface188_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, 84.18]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface191_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, -637.5]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface198_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, -635.59]} scale={[-100, 100, 95.67]} />
        <mesh geometry={nodes.polySurface201_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, -641.8]} scale={[-100, 100, 96.7]} />
        <mesh geometry={nodes.polySurface148_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -637.5]} scale={100} />
        <mesh geometry={nodes.polySurface149_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -620.35]} scale={[100, 100, 96.72]} />
        <mesh geometry={nodes.polySurface150_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -637.5]} scale={100} />
        <mesh geometry={nodes.polySurface151_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -637.5]} scale={100} />
        <mesh geometry={nodes.polySurface152_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -637.5]} scale={100} />
        <mesh geometry={nodes.polySurface153_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -637.5]} scale={100} />
        <mesh geometry={nodes.polySurface154_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -637.5]} scale={100} />
        <mesh geometry={nodes.polySurface155_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -637.5]} scale={100} />
        <mesh geometry={nodes.polySurface156_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -637.5]} scale={100} />
        <mesh geometry={nodes.polySurface157_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -637.5]} scale={100} />
        <mesh geometry={nodes.polySurface158_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -637.5]} scale={100} />
        <mesh geometry={nodes.polySurface159_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -637.5]} scale={100} />
        <mesh geometry={nodes.polySurface160_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -625.98]} scale={[100, 100, 96.81]} />
        <mesh geometry={nodes.polySurface161_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -625.98]} scale={[100, 100, 96.81]} />
        <mesh geometry={nodes.polySurface162_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -637.5]} scale={100} />
        <mesh geometry={nodes.polySurface163_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -637.5]} scale={100} />
        <mesh geometry={nodes.polySurface164_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -637.5]} scale={100} />
        <mesh geometry={nodes.polySurface176_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -438.18]} scale={[100, 100, 96.72]} />
        <mesh geometry={nodes.polySurface177_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -256.02]} scale={[100, 100, 96.72]} />
        <mesh geometry={nodes.polySurface178_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, -73.85]} scale={[100, 100, 96.72]} />
        <mesh geometry={nodes.polySurface182_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, -637.5]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface183_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, -637.5]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface186_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, -637.5]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface189_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, -637.5]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface193_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, -637.5]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface194_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, -637.5]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface195_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, -637.5]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface196_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, -637.5]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface199_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, -637.5]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface200_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, -637.5]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface202_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, -637.5]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface203_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, -637.5]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface204_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, -637.5]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface205_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, -637.5]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface143001_matt2002_0.geometry} material={materials['matt2.002']} position={[268.96, 623.77, 699.88]} scale={[65.09, 65.09, 99.49]} />
        <mesh geometry={nodes.polySurface145001_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, 81.83]} scale={[100, 100, 95.67]} />
        <mesh geometry={nodes.polySurface147001_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, 75.61]} scale={[100, 100, 96.7]} />
        <mesh geometry={nodes.polySurface165001_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, 439.33]} scale={[100, 100, 95.67]} />
        <mesh geometry={nodes.polySurface166001_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, 434.43]} scale={[100, 100, 96.7]} />
        <mesh geometry={nodes.polySurface175001_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, 801.59]} scale={100} />
        <mesh geometry={nodes.polySurface179001_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, 439.33]} scale={[-100, 100, 95.67]} />
        <mesh geometry={nodes.polySurface184001_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, 434.43]} scale={[-100, 100, 96.7]} />
        <mesh geometry={nodes.polySurface188001_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, 801.59]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface198001_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, 81.83]} scale={[-100, 100, 95.67]} />
        <mesh geometry={nodes.polySurface201001_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, 75.61]} scale={[-100, 100, 96.7]} />
        <mesh geometry={nodes.polySurface148001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 79.91]} scale={100} />
        <mesh geometry={nodes.polySurface149001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 97.07]} scale={[100, 100, 96.72]} />
        <mesh geometry={nodes.polySurface150001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 79.91]} scale={100} />
        <mesh geometry={nodes.polySurface151001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 79.91]} scale={100} />
        <mesh geometry={nodes.polySurface152001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 79.91]} scale={100} />
        <mesh geometry={nodes.polySurface153001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 79.91]} scale={100} />
        <mesh geometry={nodes.polySurface154001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 79.91]} scale={100} />
        <mesh geometry={nodes.polySurface155001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 79.91]} scale={100} />
        <mesh geometry={nodes.polySurface156001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 79.91]} scale={100} />
        <mesh geometry={nodes.polySurface157001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 79.91]} scale={100} />
        <mesh geometry={nodes.polySurface158001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 79.91]} scale={100} />
        <mesh geometry={nodes.polySurface159001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 79.91]} scale={100} />
        <mesh geometry={nodes.polySurface160001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 91.43]} scale={[100, 100, 96.81]} />
        <mesh geometry={nodes.polySurface161001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 91.43]} scale={[100, 100, 96.81]} />
        <mesh geometry={nodes.polySurface162001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 79.91]} scale={100} />
        <mesh geometry={nodes.polySurface163001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 79.91]} scale={100} />
        <mesh geometry={nodes.polySurface164001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 79.91]} scale={100} />
        <mesh geometry={nodes.polySurface176001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 279.23]} scale={[100, 100, 96.72]} />
        <mesh geometry={nodes.polySurface177001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 461.4]} scale={[100, 100, 96.72]} />
        <mesh geometry={nodes.polySurface178001_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 643.56]} scale={[100, 100, 96.72]} />
        <mesh geometry={nodes.polySurface182001_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 79.91]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface183001_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 79.91]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface186001_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 79.91]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface189001_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 79.91]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface193001_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 79.91]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface194001_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 79.91]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface195001_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 79.91]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface196001_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 79.91]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface199001_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 79.91]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface200001_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 79.91]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface202001_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 79.91]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface203001_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 79.91]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface204001_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 79.91]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface205001_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 79.91]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface143002_matt2002_0.geometry} material={materials['matt2.002']} position={[268.96, 623.77, 1413.63]} scale={[65.09, 65.09, 99.49]} />
        <mesh geometry={nodes.polySurface145002_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, 799.24]} scale={[100, 100, 95.67]} />
        <mesh geometry={nodes.polySurface147002_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, 793.02]} scale={[100, 100, 96.7]} />
        <mesh geometry={nodes.polySurface165002_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, 1156.75]} scale={[100, 100, 95.67]} />
        <mesh geometry={nodes.polySurface166002_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, 1151.84]} scale={[100, 100, 96.7]} />
        <mesh geometry={nodes.polySurface175002_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, 1519]} scale={100} />
        <mesh geometry={nodes.polySurface179002_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, 1156.75]} scale={[-100, 100, 95.67]} />
        <mesh geometry={nodes.polySurface184002_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, 1151.84]} scale={[-100, 100, 96.7]} />
        <mesh geometry={nodes.polySurface188002_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, 1519]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface198002_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, 799.24]} scale={[-100, 100, 95.67]} />
        <mesh geometry={nodes.polySurface201002_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, 793.02]} scale={[-100, 100, 96.7]} />
        <mesh geometry={nodes.polySurface148002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 797.32]} scale={100} />
        <mesh geometry={nodes.polySurface149002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 814.48]} scale={[100, 100, 96.72]} />
        <mesh geometry={nodes.polySurface150002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 797.32]} scale={100} />
        <mesh geometry={nodes.polySurface151002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 797.32]} scale={100} />
        <mesh geometry={nodes.polySurface152002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 797.32]} scale={100} />
        <mesh geometry={nodes.polySurface153002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 797.32]} scale={100} />
        <mesh geometry={nodes.polySurface154002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 797.32]} scale={100} />
        <mesh geometry={nodes.polySurface155002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 797.32]} scale={100} />
        <mesh geometry={nodes.polySurface156002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 797.32]} scale={100} />
        <mesh geometry={nodes.polySurface157002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 797.32]} scale={100} />
        <mesh geometry={nodes.polySurface158002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 797.32]} scale={100} />
        <mesh geometry={nodes.polySurface159002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 797.32]} scale={100} />
        <mesh geometry={nodes.polySurface160002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 808.85]} scale={[100, 100, 96.81]} />
        <mesh geometry={nodes.polySurface161002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 808.85]} scale={[100, 100, 96.81]} />
        <mesh geometry={nodes.polySurface162002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 797.32]} scale={100} />
        <mesh geometry={nodes.polySurface163002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 797.32]} scale={100} />
        <mesh geometry={nodes.polySurface164002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 797.32]} scale={100} />
        <mesh geometry={nodes.polySurface176002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 996.65]} scale={[100, 100, 96.72]} />
        <mesh geometry={nodes.polySurface177002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1178.81]} scale={[100, 100, 96.72]} />
        <mesh geometry={nodes.polySurface178002_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1360.98]} scale={[100, 100, 96.72]} />
        <mesh geometry={nodes.polySurface182002_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 797.32]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface183002_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 797.32]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface186002_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 797.32]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface189002_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 797.32]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface193002_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 797.32]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface194002_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 797.32]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface195002_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 797.32]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface196002_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 797.32]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface199002_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 797.32]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface200002_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 797.32]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface202002_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 797.32]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface203002_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 797.32]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface204002_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 797.32]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface205002_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 797.32]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface143003_matt2002_0.geometry} material={materials['matt2.002']} position={[268.96, 623.77, 2127.38]} scale={[65.09, 65.09, 99.49]} />
        <mesh geometry={nodes.polySurface145003_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, 1516.65]} scale={[100, 100, 95.67]} />
        <mesh geometry={nodes.polySurface147003_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, 1510.44]} scale={[100, 100, 96.7]} />
        <mesh geometry={nodes.polySurface165003_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, 1874.16]} scale={[100, 100, 95.67]} />
        <mesh geometry={nodes.polySurface166003_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, 1869.25]} scale={[100, 100, 96.7]} />
        <mesh geometry={nodes.polySurface175003_matt2002_0.geometry} material={materials['matt2.002']} position={[-70.65, -28.36, 2236.42]} scale={100} />
        <mesh geometry={nodes.polySurface179003_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, 1874.16]} scale={[-100, 100, 95.67]} />
        <mesh geometry={nodes.polySurface184003_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, 1869.25]} scale={[-100, 100, 96.7]} />
        <mesh geometry={nodes.polySurface188003_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, 2230.4]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface198003_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, 1516.65]} scale={[-100, 100, 95.67]} />
        <mesh geometry={nodes.polySurface201003_matt2002_0.geometry} material={materials['matt2.002']} position={[607.48, -28.36, 1510.44]} scale={[-100, 100, 96.7]} />
        <mesh geometry={nodes.polySurface148003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1514.74]} scale={100} />
        <mesh geometry={nodes.polySurface149003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1531.9]} scale={[100, 100, 96.72]} />
        <mesh geometry={nodes.polySurface150003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1514.74]} scale={100} />
        <mesh geometry={nodes.polySurface151003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1514.74]} scale={100} />
        <mesh geometry={nodes.polySurface152003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1514.74]} scale={100} />
        <mesh geometry={nodes.polySurface153003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1514.74]} scale={100} />
        <mesh geometry={nodes.polySurface154003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1514.74]} scale={100} />
        <mesh geometry={nodes.polySurface155003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1514.74]} scale={100} />
        <mesh geometry={nodes.polySurface156003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1514.74]} scale={100} />
        <mesh geometry={nodes.polySurface157003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1514.74]} scale={100} />
        <mesh geometry={nodes.polySurface158003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1514.74]} scale={100} />
        <mesh geometry={nodes.polySurface159003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1514.74]} scale={100} />
        <mesh geometry={nodes.polySurface160003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1526.26]} scale={[100, 100, 96.81]} />
        <mesh geometry={nodes.polySurface161003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1526.26]} scale={[100, 100, 96.81]} />
        <mesh geometry={nodes.polySurface162003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1514.74]} scale={100} />
        <mesh geometry={nodes.polySurface163003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1514.74]} scale={100} />
        <mesh geometry={nodes.polySurface164003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1514.74]} scale={100} />
        <mesh geometry={nodes.polySurface176003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1714.06]} scale={[100, 100, 96.72]} />
        <mesh geometry={nodes.polySurface177003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 1896.23]} scale={[100, 100, 96.72]} />
        <mesh geometry={nodes.polySurface178003_mat3001_0.geometry} material={materials['mat3.001']} position={[-70.65, -28.36, 2078.39]} scale={[100, 100, 96.72]} />
        <mesh geometry={nodes.polySurface182003_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 1514.74]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface183003_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 1514.74]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface186003_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 1514.74]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface189003_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 1514.74]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface193003_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 1514.74]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface194003_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 1514.74]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface195003_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 1514.74]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface196003_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 1514.74]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface199003_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 1514.74]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface200003_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 1514.74]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface202003_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 1514.74]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface203003_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 1514.74]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface204003_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 1514.74]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.polySurface205003_mat3001_0.geometry} material={materials['mat3.001']} position={[607.48, -28.36, 1514.74]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.pCube74001_matt2002_0.geometry} material={materials['matt2.002']} position={[241.65, 181.87, 2498.86]} scale={[958.52, 958.52, 3.5]} />
        <mesh geometry={nodes.polySurface160004_mat3001_0.geometry} material={materials['mat3.001']} position={[600.93, -28.36, 2734.89]} rotation={[Math.PI, 0, Math.PI]} scale={[100, 100, 96.81]} />
        <mesh geometry={nodes.polySurface161004_mat3001_0.geometry} material={materials['mat3.001']} position={[600.93, -28.36, 2734.89]} rotation={[Math.PI, 0, Math.PI]} scale={[100, 100, 96.81]} />
        <mesh geometry={nodes.polySurface160005_mat3001_0.geometry} material={materials['mat3.001']} position={[600.93, -28.36, 2017.48]} rotation={[Math.PI, 0, Math.PI]} scale={[100, 100, 96.81]} />
        <mesh geometry={nodes.polySurface161005_mat3001_0.geometry} material={materials['mat3.001']} position={[600.93, -28.36, 2017.48]} rotation={[Math.PI, 0, Math.PI]} scale={[100, 100, 96.81]} />
        <mesh geometry={nodes.polySurface160006_mat3001_0.geometry} material={materials['mat3.001']} position={[600.93, -28.36, 1300.07]} rotation={[Math.PI, 0, Math.PI]} scale={[100, 100, 96.81]} />
        <mesh geometry={nodes.polySurface161006_mat3001_0.geometry} material={materials['mat3.001']} position={[600.93, -28.36, 1300.07]} rotation={[Math.PI, 0, Math.PI]} scale={[100, 100, 96.81]} />
        <mesh geometry={nodes.polySurface160007_mat3001_0.geometry} material={materials['mat3.001']} position={[600.93, -28.36, 582.65]} rotation={[Math.PI, 0, Math.PI]} scale={[100, 100, 96.81]} />
        <mesh geometry={nodes.polySurface161007_mat3001_0.geometry} material={materials['mat3.001']} position={[600.93, -28.36, 582.65]} rotation={[Math.PI, 0, Math.PI]} scale={[100, 100, 96.81]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
