/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene.gltf
Author: re1monsen (https://sketchfab.com/re1monsen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-station-0da4a24e7edd49159737675ffcc06228
Title: Space Station
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.45, -0.1, 0]} scale={1.19}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.spacestation001_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation002_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation003_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation004_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation005_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation006_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation007_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation008_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation009_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation010_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation011_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation012_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation013_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation014_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation015_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation016_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation017_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation018_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation019_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation020_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation021_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation022_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation023_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation024_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation025_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation026_low_Main_0.geometry} material={materials.Main} position={[-658.79, -427.54, -105.87]} rotation={[-1.56, 0, 1.34]} scale={100} />
          <mesh geometry={nodes.spacestation027_low_Main_0.geometry} material={materials.Main} position={[334.66, -47.48, -855.53]} rotation={[-Math.PI / 2, 0, -1.77]} scale={100} />
          <mesh geometry={nodes.spacestation029_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation030_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation031_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation032_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation033_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation034_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.spacestation_low_Main_0.geometry} material={materials.Main} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.emit_low001_emitrED_0.geometry} material={materials.emitrED} position={[-658.79, -427.54, -105.87]} rotation={[-1.56, 0, 1.34]} scale={100} />
          <mesh geometry={nodes.emit_low_emitrED_0.geometry} material={materials.emitrED} position={[334.66, -47.48, -855.53]} rotation={[-Math.PI / 2, 0, -1.77]} scale={100} />
          <mesh geometry={nodes.emit_low002_emitrED_0.geometry} material={materials.emitrED} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
