/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene.gltf
Author: Unity Fan youtube channel (https://sketchfab.com/unityfan777)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-vehicle-027-public-domain-cc0-6c7809dbf2f945c8b216b6afb71456c4
Title: Sci-Fi Vehicle 027 - public domain (CC0)
*/
import React from 'react'
import { useGLTF } from '@react-three/drei'
// import { useTrimesh } from '@react-three/cannon'
// import CannonUtils from '../CannonUtils'

// мне удалось воссоздать физику углов для авто!!! теперь она с массой
export function AvtoFuture1(props) {
  const { nodes, materials } = useGLTF('/models/avtoFuture1/scene.gltf')
  // const args1 = useMemo(
  //   () => CannonUtils.toTrimeshProps(nodes.blocker_blocker_0.geometry),
  //   [nodes]
  // )
  // const [ref1] = useTrimesh(
  //   () => ({ args: args1, mass: 1, position: [5, -1, 6] }),
  //   useRef()
  // )

  return (
    <group {...props} dispose={null}>
      <group scale={0.01} rotation={[Math.PI, Math.PI, Math.PI]}>
        <mesh
          geometry={nodes.blocker_blocker_0.geometry}
          material={materials.blocker}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.blocker001_silver_0.geometry}
          material={materials.silver}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.blocker002_plastic_shiny_0.geometry}
          material={materials.plastic_shiny}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.blocker003_silver_0.geometry}
          material={materials.silver}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.blocker004_plastic_smoth_0.geometry}
          material={materials.plastic_smoth}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.blocker005_taillights_0.geometry}
          material={materials.taillights}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.blocker006_plastic_smoth_0.geometry}
          material={materials.plastic_smoth}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.blocker007_plastic_smoth_0.geometry}
          material={materials.plastic_smoth}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.blocker008_plastic_matte_0.geometry}
          material={materials.plastic_matte}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.blocker009_silver_0.geometry}
          material={materials.silver}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.blocker010_silver_0.geometry}
          material={materials.silver}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.blocker011_silver_0.geometry}
          material={materials.silver}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.blocker012_headlights_0.geometry}
          material={materials.headlights}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.blocker013_silver_0.geometry}
          material={materials.silver}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.blocker014_silver_0.geometry}
          material={materials.silver}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.blocker015_silver_0.geometry}
          material={materials.silver}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.blocker016_silver_0.geometry}
          material={materials.silver}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.blocker017_silver_0.geometry}
          material={materials.silver}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/avtoFuture1/scene.gltf')
