/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene.gltf
Author: nenkea (https://sketchfab.com/nenkea)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-building-1-da4d7f4c35be49baa287af0782c2171b
Title: Sci-Fi Building 1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder_Main_0.geometry} material={materials.Main} />
          <mesh geometry={nodes.Cylinder_Light_Metal_0.geometry} material={materials.Light_Metal} />
          <mesh geometry={nodes.Cylinder_Floor_0.geometry} material={materials.Floor} />
          <mesh geometry={nodes.Cylinder_Ceiling_Metal_0.geometry} material={materials.Ceiling_Metal} />
          <mesh geometry={nodes.Cylinder_Marble_0.geometry} material={materials.Marble} />
          <mesh geometry={nodes.Cylinder_Glass_realistic_Eevee_0.geometry} material={materials.Glass_realistic_Eevee} />
          <mesh geometry={nodes.Cylinder_Railing_Metal_0.geometry} material={materials.Railing_Metal} />
          <mesh geometry={nodes.Cylinder_Concrete_0.geometry} material={materials.Concrete} />
          <mesh geometry={nodes.Cylinder_Metall_Light_0.geometry} material={materials.Metall_Light} />
          <mesh geometry={nodes.Cylinder_LED_Light_0.geometry} material={materials.LED_Light} />
          <mesh geometry={nodes.Cylinder_Metall_Light_Mirror_0.geometry} material={materials.Metall_Light_Mirror} />
          <mesh geometry={nodes.Cylinder_Lights_0.geometry} material={materials.Lights} />
          <mesh geometry={nodes.Cylinder_Water_Background_0.geometry} material={materials.Water_Background} />
          <mesh geometry={nodes.Cylinder_Water_for_Eevee_0.geometry} material={materials.Water_for_Eevee} />
          <mesh geometry={nodes.Cylinder_Lights2_0.geometry} material={materials.Lights2} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
