/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene.gltf
Author: Villius (https://sketchfab.com/villius12346)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dron-0e8736c08a31438c8d090ccdcc7d0973
Title: Dron
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.2, -0.19, -3.1]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_8.geometry} material={materials.Dark_metal} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Blue_light} />
      </group>
      <group rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_13.geometry} material={materials.Light_metal} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Dark_metal} />
      </group>
      <group position={[0.66, -0.66, -0.29]} rotation={[Math.PI / 2, -Math.PI / 4, -1.16]}>
        <mesh geometry={nodes.Object_36.geometry} material={materials.Corpus} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.Dark_metal} />
      </group>
      <group position={[-0.66, -0.66, -0.29]} rotation={[-Math.PI / 2, -Math.PI / 4, 1.98]}>
        <mesh geometry={nodes.Object_39.geometry} material={materials.Corpus} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Dark_metal} />
      </group>
      <group position={[-0.6, 0.58, -0.81]} rotation={[1.02, 0.71, -1.19]}>
        <mesh geometry={nodes.Object_52.geometry} material={materials.Light_metal} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.Corpus} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.Dark_metal} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.Fire} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.Blue_light} />
      </group>
      <group position={[0.6, -0.58, -0.81]} rotation={[-1.02, -0.71, 1.95]}>
        <mesh geometry={nodes.Object_58.geometry} material={materials.Light_metal} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.Corpus} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.Dark_metal} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.Fire} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.Blue_light} />
      </group>
      <group position={[-0.6, 0.58, -0.81]} rotation={[1.02, 0.71, -1.19]}>
        <mesh geometry={nodes.Object_64.geometry} material={materials.Light_metal} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.Corpus} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.Dark_metal} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.Fire} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.Blue_light} />
      </group>
      <group position={[0.58, 0.6, -0.81]} rotation={[1.02, -0.7, -1.95]}>
        <mesh geometry={nodes.Object_70.geometry} material={materials.Light_metal} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.Corpus} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.Dark_metal} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.Fire} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.Blue_light} />
      </group>
      <group position={[-0.58, -0.6, -0.81]} rotation={[-1.02, 0.7, 1.19]}>
        <mesh geometry={nodes.Object_76.geometry} material={materials.Light_metal} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.Corpus} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.Dark_metal} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.Fire} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.Blue_light} />
      </group>
      <group position={[1.24, -0.19, -2.83]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_156.geometry} material={materials.Dark_metal} />
        <mesh geometry={nodes.Object_157.geometry} material={materials.Blue_light} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Corpus} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Corpus} rotation={[-1.57, 0.8, 0.8]} scale={0.27} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.Dark_metal} rotation={[-Math.PI / 2, 1.4, Math.PI]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Dark_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Corpus} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Blue_light} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Light_metal} position={[0, -0.52, 0.84]} rotation={[2.04, Math.PI / 2, 0]} scale={0.02} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Dark_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.Light_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.Blue_light} rotation={[-Math.PI / 2, 1.4, Math.PI]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Light_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.Dark_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.Dark_metal} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.Dark_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.Corpus} rotation={[1.57, 0.77, -2.34]} scale={0.27} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.Corpus} rotation={[1.57, -0.8, -2.34]} scale={0.27} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.Corpus} rotation={[-1.57, -0.77, 0.8]} scale={0.27} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.Corpus} position={[-2.76, 2.7, -2.03]} rotation={[1.03, 0.69, -1.2]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.Light_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_84.geometry} material={materials.Dark_metal} scale={0.22} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.Dark_metal} scale={0.22} />
      <mesh geometry={nodes.Object_88.geometry} material={materials.Dark_metal} position={[3.74, 0, 0]} scale={0.22} />
      <mesh geometry={nodes.Object_90.geometry} material={materials.Dark_metal} scale={0.22} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.Fire} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.Dark_metal} position={[0, 0, -0.86]} rotation={[0, 0, 2.36]} scale={0.09} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.Dark_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.Dark_metal} position={[-0.45, -0.62, 2.29]} rotation={[-1.38, 0.02, 0.1]} scale={0.01} />
      <mesh geometry={nodes.Object_100.geometry} material={materials.Dark_metal} position={[-0.45, -0.66, 2.26]} rotation={[-0.83, 0.07, 0.08]} scale={0.01} />
      <mesh geometry={nodes.Object_102.geometry} material={materials.Dark_metal} position={[-0.46, -0.69, 2.19]} rotation={[-0.35, 0.1, 0.04]} scale={0.01} />
      <mesh geometry={nodes.Object_104.geometry} material={materials.Dark_metal} position={[-0.46, -0.37, 2.2]} rotation={[0.67, 0.08, 3.08]} scale={0.01} />
      <mesh geometry={nodes.Object_106.geometry} material={materials.Dark_metal} position={[-0.46, -0.36, 2.15]} rotation={[0.11, 0.1, 3.13]} scale={0.01} />
      <mesh geometry={nodes.Object_108.geometry} material={materials.Dark_metal} position={[-0.47, -0.39, 2.08]} rotation={[-0.37, 0.1, -3.1]} scale={0.01} />
      <mesh geometry={nodes.Object_110.geometry} material={materials.Dark_metal} position={[-0.59, -0.5, 2.26]} rotation={[-0.43, 1.12, -1.49]} scale={0.01} />
      <mesh geometry={nodes.Object_112.geometry} material={materials.Dark_metal} position={[-0.62, -0.51, 2.22]} rotation={[-0.38, 0.57, -1.53]} scale={0.01} />
      <mesh geometry={nodes.Object_114.geometry} material={materials.Dark_metal} position={[-0.62, -0.54, 2.15]} rotation={[-0.36, 0.09, -1.53]} scale={0.01} />
      <mesh geometry={nodes.Object_116.geometry} material={materials.Dark_metal} position={[-0.32, -0.5, 2.23]} rotation={[-0.31, -0.92, 1.63]} scale={0.01} />
      <mesh geometry={nodes.Object_118.geometry} material={materials.Dark_metal} position={[-0.3, -0.51, 2.18]} rotation={[-0.34, -0.37, 1.61]} scale={0.01} />
      <mesh geometry={nodes.Object_120.geometry} material={materials.Dark_metal} position={[-0.3, -0.54, 2.12]} rotation={[-0.36, 0.11, 1.61]} scale={0.01} />
      <mesh geometry={nodes.Object_122.geometry} material={materials.Dark_metal} position={[-0.48, -0.6, 1.97]} rotation={[-Math.PI, 1.47, -1.93]} scale={0.09} />
      <mesh geometry={nodes.Object_124.geometry} material={materials.Dark_metal} position={[0.99, -0.77, 2.23]} rotation={[-1.29, -0.48, 0.23]} scale={0.01} />
      <mesh geometry={nodes.Object_126.geometry} material={materials.Dark_metal} position={[1, -0.8, 2.19]} rotation={[-0.72, -0.29, 0.45]} scale={0.01} />
      <mesh geometry={nodes.Object_128.geometry} material={materials.Dark_metal} position={[1.01, -0.82, 2.12]} rotation={[-0.29, -0.07, 0.53]} scale={0.01} />
      <mesh geometry={nodes.Object_130.geometry} material={materials.Dark_metal} position={[0.85, -0.54, 2.15]} rotation={[0.63, 0.4, -2.78]} scale={0.01} />
      <mesh geometry={nodes.Object_132.geometry} material={materials.Dark_metal} position={[0.84, -0.54, 2.1]} rotation={[0.11, 0.16, -2.63]} scale={0.01} />
      <mesh geometry={nodes.Object_134.geometry} material={materials.Dark_metal} position={[0.85, -0.56, 2.03]} rotation={[-0.31, -0.08, -2.62]} scale={0.01} />
      <mesh geometry={nodes.Object_136.geometry} material={materials.Dark_metal} position={[0.8, -0.72, 2.2]} rotation={[-0.94, 0.77, -0.8]} scale={0.01} />
      <mesh geometry={nodes.Object_138.geometry} material={materials.Dark_metal} position={[0.79, -0.75, 2.16]} rotation={[-0.54, 0.33, -1.01]} scale={0.01} />
      <mesh geometry={nodes.Object_140.geometry} material={materials.Dark_metal} position={[0.79, -0.77, 2.09]} rotation={[-0.29, -0.08, -1.04]} scale={0.01} />
      <mesh geometry={nodes.Object_142.geometry} material={materials.Dark_metal} position={[1.04, -0.59, 2.18]} rotation={[0.45, -0.89, 2.48]} scale={0.01} />
      <mesh geometry={nodes.Object_144.geometry} material={materials.Dark_metal} position={[1.06, -0.59, 2.13]} rotation={[-0.04, -0.47, 2.17]} scale={0.01} />
      <mesh geometry={nodes.Object_146.geometry} material={materials.Dark_metal} position={[1.07, -0.61, 2.06]} rotation={[-0.3, -0.06, 2.1]} scale={0.01} />
      <mesh geometry={nodes.Object_148.geometry} material={materials.Dark_metal} position={[0.94, -0.74, 1.9]} rotation={[-1.74, 1.04, 3]} scale={0.09} />
      <mesh geometry={nodes.Object_150.geometry} material={materials.Dark_metal} position={[-0.48, -0.61, 1.94]} rotation={[-Math.PI, 1.47, -1.93]} scale={0.1} />
      <mesh geometry={nodes.Object_152.geometry} material={materials.Dark_metal} position={[-0.48, -0.61, 1.94]} rotation={[-Math.PI, 1.47, -1.93]} scale={0.1} />
      <mesh geometry={nodes.Object_154.geometry} material={materials.Dark_metal} position={[0.94, -0.75, 1.87]} rotation={[-1.74, 1.04, 3]} scale={0.1} />
      <mesh geometry={nodes.Object_159.geometry} material={materials.Dark_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_161.geometry} material={materials.Dark_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
