/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene.gltf
Author: re1monsen (https://sketchfab.com/re1monsen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/12k-followers-celebration-sci-fi-grenade-4a74b893b580489f8d961dc75148a234
Title: 1.2k Followers Celebration - Sci Fi Grenade
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function AnomalTop(props) {
  const { nodes, materials } = useGLTF('/models/test/anomalTop/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.1}>
          <mesh
            geometry={nodes.gremade002_low_grenade_0.geometry}
            material={materials.grenade}
            position={[1.4, -0.51, 0]}
            rotation={[-Math.PI / 2, 0.7, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.gremade001_low_grenade_0.geometry}
            material={materials.grenade}
            position={[1.4, -0.51, 0]}
            rotation={[-Math.PI / 2, 0.7, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.gremade010_low_grenade_0.geometry}
            material={materials.grenade}
            position={[1.51, -0.61, 0]}
            rotation={[-Math.PI / 2, 0.7, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.gremade003_low_grenade_0.geometry}
            material={materials.grenade}
            position={[1.4, -0.51, 0]}
            rotation={[-Math.PI / 2, 0.7, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.gremade004_low_grenade_0.geometry}
            material={materials.grenade}
            position={[1.4, -0.51, 0]}
            rotation={[-Math.PI / 2, 0.7, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.gremade005_low_grenade_0.geometry}
            material={materials.grenade}
            position={[1.71, -0.15, 0]}
            rotation={[-Math.PI / 2, 0.7, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.gremade006_low_grenade_0.geometry}
            material={materials.grenade}
            position={[1.4, -0.51, 0]}
            rotation={[-Math.PI / 2, 0.7, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.gremade007_low_grenade_0.geometry}
            material={materials.grenade}
            position={[1.4, -0.51, 0]}
            rotation={[-Math.PI / 2, 0.7, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.gremade008_low_grenade_0.geometry}
            material={materials.grenade}
            position={[1.4, -0.51, 0]}
            rotation={[-Math.PI / 2, 0.7, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.gremade009_low_grenade_0.geometry}
            material={materials.grenade}
            position={[2.36, 0.63, 0]}
            rotation={[-Math.PI / 2, 0.7, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.gremade011_low_grenade_0.geometry}
            material={materials.grenade}
            position={[1.4, -0.51, 0]}
            rotation={[-Math.PI / 2, 0.7, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.gremade_low_grenade_0.geometry}
            material={materials.grenade}
            position={[1.4, -0.51, 0]}
            rotation={[-Math.PI / 2, 0.7, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.gremade012_low_grenade_0.geometry}
            material={materials.grenade}
            position={[1.4, -0.51, 0]}
            rotation={[-Math.PI / 2, 0.7, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.gremade013_low_grenade_0.geometry}
            material={materials.grenade}
            position={[-19.18, -24.91, 0]}
            rotation={[-Math.PI / 2, 0.7, 0]}
            scale={160.37}
          />
          <mesh
            geometry={nodes.ground_low_ground_0.geometry}
            material={materials.ground}
            position={[0, -65.89, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.glass_low_Glass_0.geometry}
            material={materials.Glass}
            rotation={[-Math.PI / 2, 0.7, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.liquid_low_liquid_0.geometry}
            material={materials.liquid}
            rotation={[-Math.PI / 2, 0.02, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/test/anomalTop/scene.gltf')
