/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene.gltf
Author: Egor Liashchuk (https://sketchfab.com/egorliashchuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/base-yrs-25c68dc285aa42a7941f2cb7a2df5b3d
Title: Base YRS
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function BaseYrs(props) {
  const { nodes, materials } = useGLTF('/models/base_yrs/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[694.96, 4.46, 2237.97]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Gandr_floor002_Base_0.geometry}
            material={materials.Base}
          />
          <mesh
            geometry={nodes.Gandr_floor002_Material002_0.geometry}
            material={materials['Material.002']}
          />
        </group>
        <group
          position={[608.61, 1361.13, -218.89]}
          rotation={[-Math.PI / 2, 0, 0.09]}
          scale={100}
        >
          <mesh
            geometry={nodes.Building_1002_Base_0.geometry}
            material={materials.Base}
          />
          <mesh
            geometry={nodes.Building_1002_Material002_0.geometry}
            material={materials['Material.002']}
          />
        </group>
        <group
          position={[739.12, 1049.45, 5097.83]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Building_2002_Base_0.geometry}
            material={materials.Base}
          />
          <mesh
            geometry={nodes.Building_2002_Material002_0.geometry}
            material={materials['Material.002']}
          />
        </group>
        <group
          position={[-1519.11, 4167.14, -2830.7]}
          rotation={[-Math.PI / 2, 0, 0.66]}
          scale={100}
        >
          <mesh
            geometry={nodes.Building_5002_Base_0.geometry}
            material={materials.Base}
          />
          <mesh
            geometry={nodes.Building_5002_Material002_0.geometry}
            material={materials['Material.002']}
          />
        </group>
        <group
          position={[590.45, 2327.81, -3646.96]}
          rotation={[-Math.PI / 2, 0, 0.09]}
          scale={100}
        >
          <mesh
            geometry={nodes.Building_4002_Base_0.geometry}
            material={materials.Base}
          />
          <mesh
            geometry={nodes.Building_4002_Material002_0.geometry}
            material={materials['Material.002']}
          />
        </group>
        <group
          position={[1044.67, 570.57, -2172.59]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Building_3002_Base_0.geometry}
            material={materials.Base}
          />
          <mesh
            geometry={nodes.Building_3002_Material002_0.geometry}
            material={materials['Material.002']}
          />
        </group>
        <group
          position={[3404.75, 254.68, -2063.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.barrels002_Base_0.geometry}
            material={materials.Base}
          />
          <mesh
            geometry={nodes.barrels002_Material002_0.geometry}
            material={materials['Material.002']}
          />
        </group>
        <group
          position={[688.07, 3.73, 5412.84]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Floor002_Base_0.geometry}
            material={materials.Base}
          />
          <mesh
            geometry={nodes.Floor002_Material002_0.geometry}
            material={materials['Material.002']}
          />
        </group>
        <group
          position={[-385.93, 2433.98, 5207.84]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Building_6002_Base_0.geometry}
            material={materials.Base}
          />
          <mesh
            geometry={nodes.Building_6002_Material002_0.geometry}
            material={materials['Material.002']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/base_yrs/scene.gltf')
