/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene.gltf
Author: re1monsen (https://sketchfab.com/re1monsen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/11k-celebration-class-5-weapon-rack-0e2010b6607b49738a25346908dfa879
Title: 1.1k Celebration - Class 5 Weapon Rack
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function RobotAnime(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(
    '/models/test/RobotAnime/scene.gltf'
  )
  const { actions } = useAnimations(animations, group)
  console.log(actions)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Man_Walking_2_Man_Walking_B_67"
                position={[-1.19, -0.03, 1.52]}
                rotation={[Math.PI / 2, 0, -2.13]}
                scale={0.01}
              >
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group
                    name="Man_Walking_2_8_Mesh_66_correction"
                    position={[96.35, 263.8, -3.87]}
                    rotation={[Math.PI / 2, -1.01, -Math.PI]}
                    scale={145.94}
                  >
                    <group name="Man_Walking_2_8_Mesh_66" />
                  </group>
                  <skinnedMesh
                    name="Object_75"
                    geometry={nodes.Object_75.geometry}
                    material={materials.man_walking_b}
                    skeleton={nodes.Object_75.skeleton}
                  />
                </group>
              </group>
              <group name="rack001_low_69">
                <mesh
                  name="Object_79"
                  geometry={nodes.Object_79.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack002_low_70">
                <mesh
                  name="Object_81"
                  geometry={nodes.Object_81.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack003_low_71">
                <mesh
                  name="Object_83"
                  geometry={nodes.Object_83.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack004_low_72">
                <mesh
                  name="Object_85"
                  geometry={nodes.Object_85.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack005_low_73">
                <mesh
                  name="Object_87"
                  geometry={nodes.Object_87.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack008_low_76" rotation={[0, 0.47, 0]}>
                <mesh
                  name="Object_93"
                  geometry={nodes.Object_93.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack009_low_77">
                <mesh
                  name="Object_95"
                  geometry={nodes.Object_95.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack010_low_78">
                <mesh
                  name="Object_97"
                  geometry={nodes.Object_97.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack015_low_83" rotation={[0, -0.4, 0]}>
                <mesh
                  name="Object_107"
                  geometry={nodes.Object_107.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack016_low_84" rotation={[0, -0.4, 0]}>
                <mesh
                  name="Object_109"
                  geometry={nodes.Object_109.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack017_low_85" rotation={[0, -0.4, 0]}>
                <mesh
                  name="Object_111"
                  geometry={nodes.Object_111.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack018_low_86" rotation={[0, -0.4, 0]}>
                <mesh
                  name="Object_113"
                  geometry={nodes.Object_113.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack025_low_92">
                <mesh
                  name="Object_125"
                  geometry={nodes.Object_125.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack026_low_93">
                <mesh
                  name="Object_127"
                  geometry={nodes.Object_127.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack027_low_94" rotation={[Math.PI, -0.09, Math.PI]}>
                <mesh
                  name="Object_129"
                  geometry={nodes.Object_129.geometry}
                  material={materials.grid}
                />
                <mesh
                  name="Object_130"
                  geometry={nodes.Object_130.geometry}
                  material={materials.grid}
                />
              </group>
              <group name="rack028_low_95">
                <mesh
                  name="Object_132"
                  geometry={nodes.Object_132.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack029_low_96" rotation={[0, 0.47, 0]}>
                <mesh
                  name="Object_134"
                  geometry={nodes.Object_134.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack030_low_97" rotation={[0, 0.47, 0]}>
                <mesh
                  name="Object_136"
                  geometry={nodes.Object_136.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack031_low_98" rotation={[0, 0.47, 0]}>
                <mesh
                  name="Object_138"
                  geometry={nodes.Object_138.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack032_low_99" rotation={[0, 0.47, 0]}>
                <mesh
                  name="Object_140"
                  geometry={nodes.Object_140.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack033_low_100" rotation={[0, -0.4, 0]}>
                <mesh
                  name="Object_142"
                  geometry={nodes.Object_142.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="ground_low_0" position={[0, -0.03, 0]}>
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={materials.ground}
                />
              </group>
              <group name="rack011_low_68">
                <mesh
                  name="Object_77"
                  geometry={nodes.Object_77.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack006_low_74">
                <mesh
                  name="Object_89"
                  geometry={nodes.Object_89.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack007_low_75">
                <mesh
                  name="Object_91"
                  geometry={nodes.Object_91.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack012_low_79">
                <mesh
                  name="Object_99"
                  geometry={nodes.Object_99.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack014_low_80">
                <mesh
                  name="Object_101"
                  geometry={nodes.Object_101.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack013_low_81">
                <mesh
                  name="Object_103"
                  geometry={nodes.Object_103.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack022_low_82">
                <mesh
                  name="Object_105"
                  geometry={nodes.Object_105.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack020_low_87">
                <mesh
                  name="Object_115"
                  geometry={nodes.Object_115.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack021_low_88">
                <mesh
                  name="Object_117"
                  geometry={nodes.Object_117.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack_low_89">
                <mesh
                  name="Object_119"
                  geometry={nodes.Object_119.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack023_low_90">
                <mesh
                  name="Object_121"
                  geometry={nodes.Object_121.geometry}
                  material={materials.rack}
                />
              </group>
              <group name="rack024_low_91">
                <mesh
                  name="Object_123"
                  geometry={nodes.Object_123.geometry}
                  material={materials.rack}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/test/RobotAnime/scene.gltf')
