/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene.gltf
Author: FPSunreal (https://sketchfab.com/FPSunreal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-station-edf17c3d57584cf2acefc72ecccb8058
Title: Space station
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model2(props) {
  const { nodes, materials } = useGLTF(
    '/models/test/space_station(1)/scene.gltf'
  )
  return (
    <group {...props} dispose={null}>
      <group scale={1}>
        <mesh
          geometry={nodes['Gate+engine_gate+engine_0'].geometry}
          material={materials.gateengine}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={50}
        />
        <mesh
          geometry={nodes.Station_space_station_0.geometry}
          material={materials.space_station}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={50}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/test/space_station(1)/scene.gltf')
