/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene.gltf
Author: Sousinho (https://sketchfab.com/sousinho)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-portal-a2500f92c26142c6a5066d47cbf14d1b
Title: Sci-fi Portal
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ScifiPortal(props) {
  const { nodes, materials } = useGLTF('/models/sci-fi_portal/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.outside_ring002_rings_0.geometry}
          material={materials.rings}
          position={[-56.68, 4.44, -1786.22]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.fuse_box004_platform_0.geometry}
          material={materials.platform}
          position={[-1196.91, -418.78, -2399.39]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/sci-fi_portal/scene.gltf')
