/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene.gltf
Author: NepsterCZ (https://sketchfab.com/NepsterCZ)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/stargate-uss-prometheus-bc-303-88941cb7d761421f9bdfebe651311dda
Title: Stargate - USS Prometheus | BC-303
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function StargatePrometheus(props) {
  const { nodes, materials } = useGLTF('/models/stargate_prometheus/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.34}>
        <group position={[1.8, -63.83, 34.56]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh
            geometry={nodes.Prometheus_0.geometry}
            material={materials.Hull}
          />
          <mesh
            geometry={nodes.Prometheus_0_1.geometry}
            material={materials.Hull}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/stargate_prometheus/scene.gltf')
